#!/usr/bin/env python3
"""test_scan_and_adjudicate.py — offline/synthetic tests for
scan_perceptual_duplicates.py and adjudicate_pairs.py.

Every image used here is a synthetic, in-memory image generated by PIL/
NumPy -- never a real dataset photograph. Metadata-leakage tests use only
hand-built CSV fixtures.
"""
from __future__ import annotations

import argparse
import io
import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import numpy as np
from PIL import Image

import manual_review_contract as mrc  # noqa: E402
import perceptual_hash as ph  # noqa: E402
import scan_perceptual_duplicates as spd  # noqa: E402
import adjudicate_pairs as adj  # noqa: E402
from test_manual_review_fixtures import build_tiny_review_fixture  # noqa: E402


def synthetic_bytes(seed: int, size=(48, 48)) -> bytes:
    rng = np.random.RandomState(seed)
    arr = (rng.rand(size[1], size[0], 3) * 255).astype("uint8")
    img = Image.fromarray(arr, "RGB")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def _row(dataset, slug, split, uuid, photo_id, sha256, species="Sp X", taxon_id="1"):
    identity = spd.row_identity(dataset, slug, split, str(photo_id))
    return {"dataset": dataset, "slug": slug, "split": split, "species": species, "taxon_id": taxon_id,
            "observation_uuid": uuid, "photo_id": str(photo_id), "sha256": sha256, "identity": identity}


class TestLoadIdentityRows(unittest.TestCase):
    def test_metadata_only_load(self):
        import csv
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "m.csv"
            with path.open("w", newline="", encoding="utf-8") as fh:
                w = csv.DictWriter(fh, fieldnames=["slug", "species", "taxon_id", "observation_uuid",
                                                   "photo_id", "sha256", "split"])
                w.writeheader()
                w.writerow({"slug": "s", "species": "Sp", "taxon_id": "1", "observation_uuid": "u1",
                           "photo_id": "5", "sha256": "a" * 64, "split": "known"})
            rows = spd.load_identity_rows(path, "benchmark_v1")
        self.assertEqual(len(rows), 1)
        self.assertEqual(rows[0]["identity"], "benchmark_v1:s:known:5")

    def test_missing_field_rejected(self):
        import csv
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "m.csv"
            with path.open("w", newline="", encoding="utf-8") as fh:
                w = csv.DictWriter(fh, fieldnames=["slug", "species", "taxon_id", "photo_id", "sha256"])
                w.writeheader()
                w.writerow({"slug": "s", "species": "Sp", "taxon_id": "1", "photo_id": "5", "sha256": "a" * 64})
            with self.assertRaises(spd.ScanError):
                spd.load_identity_rows(path, "benchmark_v1", default_split="known")


class TestMetadataLeakage(unittest.TestCase):
    def test_same_uuid_across_domains_detected(self):
        shared_uuid = "shared-uuid-1"
        rows_by_domain = {
            "expansion_train": [_row("northeast_expansion_v1", "s1", "train", shared_uuid, 1, "a" * 64)],
            "final_test": [_row("northeast_final_test_v1", "s1", "final_test", shared_uuid, 2, "b" * 64)],
        }
        findings = spd.find_metadata_leakage(rows_by_domain)
        self.assertEqual(len(findings), 1)
        self.assertEqual(findings[0]["observation_uuid"], shared_uuid)
        self.assertEqual(set(findings[0]["domains"]), {"expansion_train", "final_test"})

    def test_same_uuid_within_one_domain_is_not_leakage(self):
        rows_by_domain = {
            "d1": [_row("d1", "s1", "train", "u1", 1, "a" * 64), _row("d1", "s1", "train", "u1", 2, "b" * 64)],
        }
        self.assertEqual(spd.find_metadata_leakage(rows_by_domain), [])

    def test_distinct_uuids_produce_no_finding(self):
        rows_by_domain = {
            "d1": [_row("d1", "s1", "train", "u1", 1, "a" * 64)],
            "d2": [_row("d2", "s1", "train", "u2", 2, "b" * 64)],
        }
        self.assertEqual(spd.find_metadata_leakage(rows_by_domain), [])

    def test_reported_independently_of_photo_difference(self):
        shared_uuid = "shared-uuid-2"
        rows_by_domain = {
            "d1": [_row("d1", "s1", "train", shared_uuid, 100, "a" * 64)],
            "d2": [_row("d2", "s1", "train", shared_uuid, 200, "f" * 64)],
        }
        findings = spd.find_metadata_leakage(rows_by_domain)
        self.assertEqual(len(findings), 1)


class TestIndexedEqualsBruteForce(unittest.TestCase):
    """Proves generate_candidate_pairs_indexed produces the EXACT same set
    of pairs as generate_candidate_pairs_bruteforce, across randomized
    synthetic fixtures -- both within-set (exclude_self) and cross-set."""

    def _random_hash_row(self, rng, dataset, i):
        identity = f"{dataset}:s:split:{i}"
        return identity, {
            "phashes": [rng.getrandbits(64) for _ in range(8)],
            "dhashes": [rng.getrandbits(64) for _ in range(8)],
        }

    def test_cross_set_randomized_fixture(self):
        import random
        rng = random.Random(777)
        rows_a, hashes_a = [], {}
        for i in range(15):
            identity, h = self._random_hash_row(rng, "a", i)
            rows_a.append({"identity": identity})
            hashes_a[identity] = h
        rows_b, hashes_b = [], {}
        for i in range(20):
            identity, h = self._random_hash_row(rng, "b", i)
            rows_b.append({"identity": identity})
            hashes_b[identity] = h
        # force a handful of guaranteed close pairs
        for i in range(4):
            base = hashes_a[rows_a[i]["identity"]]
            close_identity = f"b:close:{i}"
            rows_b.append({"identity": close_identity})
            hashes_b[close_identity] = {
                "phashes": [v ^ 0b111 for v in base["phashes"]],  # 3-bit flips -> within phash radius 10
                "dhashes": [rng.getrandbits(64) for _ in range(8)],
            }

        brute = spd.generate_candidate_pairs_bruteforce(rows_a, hashes_a, rows_b, hashes_b)
        indexed = spd.generate_candidate_pairs_indexed(rows_a, hashes_a, rows_b, hashes_b)
        self.assertEqual(
            {(p["identity_a"], p["identity_b"]) for p in brute},
            {(p["identity_a"], p["identity_b"]) for p in indexed},
        )
        self.assertGreater(len(brute), 0, "fixture must actually exercise some matches")
        # distances must agree exactly too
        brute_by_pair = {(p["identity_a"], p["identity_b"]): p for p in brute}
        for p in indexed:
            key = (p["identity_a"], p["identity_b"])
            self.assertEqual(p["phash_distance"], brute_by_pair[key]["phash_distance"])
            self.assertEqual(p["dhash_distance"], brute_by_pair[key]["dhash_distance"])

    def test_within_set_randomized_fixture_excludes_self_pairs(self):
        import random
        rng = random.Random(4242)
        rows, hashes = [], {}
        for i in range(25):
            identity, h = self._random_hash_row(rng, "w", i)
            rows.append({"identity": identity})
            hashes[identity] = h
        for i in range(3):
            base = hashes[rows[i]["identity"]]
            hashes[rows[i + 10]["identity"]] = {
                "phashes": [v ^ 0b11 for v in base["phashes"]],
                "dhashes": hashes[rows[i + 10]["identity"]]["dhashes"],
            }

        brute = spd.generate_candidate_pairs_bruteforce(rows, hashes, rows, hashes, exclude_self=True)
        indexed = spd.generate_candidate_pairs_indexed(rows, hashes, rows, hashes, exclude_self=True)
        self.assertEqual(
            {(p["identity_a"], p["identity_b"]) for p in brute},
            {(p["identity_a"], p["identity_b"]) for p in indexed},
        )
        for p in indexed:
            self.assertNotEqual(p["identity_a"], p["identity_b"])

    def test_real_synthetic_images_indexed_matches_bruteforce(self):
        # A small real-image fixture (not just hand-built hash ints).
        base_bytes = synthetic_bytes(1, size=(64, 64))
        base_sha = ph.sha256_bytes(base_bytes)
        row_a = _row("d1", "s1", "train", "u1", 1, base_sha)
        hashes_a = {row_a["identity"]: ph.compute_all_hashes(base_bytes, base_sha)}

        img = Image.open(io.BytesIO(base_bytes))
        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=75)
        derived_bytes = buf.getvalue()
        derived_sha = ph.sha256_bytes(derived_bytes)
        row_b1 = _row("d2", "s1", "final_test", "u1", 2, derived_sha)
        hashes_b1 = {row_b1["identity"]: ph.compute_all_hashes(derived_bytes, derived_sha)}

        other_bytes = synthetic_bytes(999, size=(64, 64))
        other_sha = ph.sha256_bytes(other_bytes)
        row_b2 = _row("d2", "s2", "final_test", "u2", 3, other_sha)
        hashes_b2 = {row_b2["identity"]: ph.compute_all_hashes(other_bytes, other_sha)}

        hashes_b = {**hashes_b1, **hashes_b2}
        brute = spd.generate_candidate_pairs_bruteforce([row_a], hashes_a, [row_b1, row_b2], hashes_b)
        indexed = spd.generate_candidate_pairs_indexed([row_a], hashes_a, [row_b1, row_b2], hashes_b)
        self.assertEqual(
            {(p["identity_a"], p["identity_b"]) for p in brute},
            {(p["identity_a"], p["identity_b"]) for p in indexed},
        )
        self.assertIn((row_a["identity"], row_b1["identity"]),
                      {(p["identity_a"], p["identity_b"]) for p in indexed})

    def test_within_set_two_row_regression_exactly_one_canonical_candidate(self):
        # Item 2: two rows, identical hashes -- the within-set search must
        # examine the one unordered pair exactly once, never emit both
        # A->B and B->A under the same pair_id.
        h = {"phashes": [0] * 8, "dhashes": [0] * 8}
        rows = [{"identity": "z-row"}, {"identity": "a-row"}]  # deliberately NOT pre-sorted
        hashes = {"z-row": h, "a-row": dict(h)}

        indexed = spd.generate_candidate_pairs_within_indexed(rows, hashes)
        self.assertEqual(len(indexed), 1)
        pair = indexed[0]
        self.assertEqual((pair["identity_a"], pair["identity_b"]), ("a-row", "z-row"))  # canonical sorted order
        self.assertEqual(pair["pair_id"], mrc.compute_pair_id("a-row", "z-row"))
        self.assertEqual(pair["phash_distance"], 0)
        self.assertEqual(pair["dhash_distance"], 0)

        # The RAW (non-canonicalized) indexed search would have produced
        # both directions under the same pair_id -- prove that's exactly
        # what canonicalization collapsed.
        raw = spd.generate_candidate_pairs_indexed(rows, hashes, rows, hashes, exclude_self=True)
        self.assertEqual(len(raw), 2)
        self.assertEqual({p["pair_id"] for p in raw}, {pair["pair_id"]})

    def test_within_set_indexed_matches_bruteforce_under_unordered_semantics(self):
        import random
        rng = random.Random(9191)
        rows, hashes = [], {}
        for i in range(20):
            identity, h = self._random_hash_row(rng, "w", i)
            rows.append({"identity": identity})
            hashes[identity] = h
        for i in range(4):
            base = hashes[rows[i]["identity"]]
            hashes[rows[i + 10]["identity"]] = {
                "phashes": [v ^ 0b11 for v in base["phashes"]],
                "dhashes": hashes[rows[i + 10]["identity"]]["dhashes"],
            }

        brute = spd.generate_candidate_pairs_within_bruteforce(rows, hashes)
        indexed = spd.generate_candidate_pairs_within_indexed(rows, hashes)
        self.assertEqual(brute, indexed)  # exact equality: same pair_ids, same canonical order, same distances
        self.assertGreater(len(indexed), 0, "fixture must actually exercise some matches")
        # No pair_id appears more than once (unordered semantics honored).
        pair_ids = [p["pair_id"] for p in indexed]
        self.assertEqual(len(pair_ids), len(set(pair_ids)))
        for p in indexed:
            self.assertLess(p["identity_a"], p["identity_b"])


class TestStopConditions(unittest.TestCase):
    def test_confirmed_same_source_in_stop_domain_triggers_stop(self):
        result = spd.evaluate_stop_conditions(
            "expansion_train_vs_final_test", confirmed_same_source_pair_ids={"pair-1"},
            candidate_pairs=[{"pair_id": "pair-1"}], leakage_findings=[])
        self.assertTrue(result["stop_before_inference"])
        self.assertIn(mrc.STOP_REASON_SAME_SOURCE_IMAGE, result["reasons"])

    def test_leakage_in_stop_domain_triggers_stop(self):
        result = spd.evaluate_stop_conditions(
            "final_test_vs_unknown_test_v1", confirmed_same_source_pair_ids=set(),
            candidate_pairs=[], leakage_findings=[{"observation_uuid": "u1"}])
        self.assertTrue(result["stop_before_inference"])
        self.assertIn(mrc.STOP_REASON_MATCHING_OBSERVATION_UUID, result["reasons"])

    def test_mere_candidate_without_confirmation_does_not_stop(self):
        result = spd.evaluate_stop_conditions(
            "expansion_train_vs_final_test", confirmed_same_source_pair_ids=set(),
            candidate_pairs=[{"pair_id": "pair-1"}], leakage_findings=[])
        self.assertFalse(result["stop_before_inference"])

    def test_non_stop_domain_never_stops(self):
        result = spd.evaluate_stop_conditions(
            "within_benchmark_v1", confirmed_same_source_pair_ids={"pair-1"},
            candidate_pairs=[{"pair_id": "pair-1"}], leakage_findings=[{"observation_uuid": "u1"}])
        self.assertFalse(result["stop_before_inference"])

    def test_every_stop_domain_recognized(self):
        for domain_name in mrc.STOP_BEFORE_INFERENCE_DOMAINS:
            with self.subTest(domain=domain_name):
                result = spd.evaluate_stop_conditions(
                    domain_name, confirmed_same_source_pair_ids={"p"},
                    candidate_pairs=[{"pair_id": "p"}], leakage_findings=[])
                self.assertTrue(result["stop_before_inference"])


class _ScanFixtureTestCase(unittest.TestCase):
    def setUp(self):
        self._tmpdir = tempfile.TemporaryDirectory()
        self.repo = Path(self._tmpdir.name)
        self.fx = build_tiny_review_fixture(self, self.repo)
        self.verified = mrc.load_and_verify_contract(self.repo)

    def tearDown(self):
        self._tmpdir.cleanup()

    def _args(self, **overrides):
        d = dict(repo=self.repo)
        d.update(overrides)
        return argparse.Namespace(**d)


def _fake_load_domain_part_rows(repo, verified, part):
    """Test stand-in: the three queue-backed parts resolve from the
    fixture's own queue rows (real, metadata-only); the five
    other-evidence parts have no manifest in this tiny fixture repo, so
    they resolve to empty (their real loading path is exercised
    separately in TestLoadIdentityRows, against a real tiny CSV)."""
    if part == mrc.DOMAIN_PART_EXPANSION_TRAIN:
        rows = [r for r in verified["queue_rows"] if r["dataset"] == mrc.EXPANSION_DATASET
               and r["split"] == mrc.EXPANSION_TRAIN_SPLIT]
    elif part == mrc.DOMAIN_PART_EXPANSION_DEVELOPMENT:
        rows = [r for r in verified["queue_rows"] if r["dataset"] == mrc.EXPANSION_DATASET
               and r["split"] == mrc.EXPANSION_DEV_SPLIT]
    elif part == mrc.DOMAIN_PART_FINAL_TEST:
        rows = [r for r in verified["queue_rows"] if r["dataset"] == mrc.FINAL_TEST_DATASET]
    else:
        rows = []
    return rows


class TestScanPreflight(_ScanFixtureTestCase):
    def test_preflight_reports_estimate_without_opening_images(self):
        real_open = Path.open
        opened = []

        def spy(self, *a, **kw):
            opened.append(str(self))
            return real_open(self, *a, **kw)

        with mock.patch.object(spd, "load_domain_part_rows", side_effect=_fake_load_domain_part_rows):
            with mock.patch.object(Path, "open", spy):
                result = spd.cmd_preflight(self._args())
        self.assertTrue(result["ok"])
        self.assertEqual(len(result["domain_estimates"]), 36)
        image_like = [p for p in opened if p.lower().endswith((".jpg", ".jpeg", ".png"))]
        self.assertEqual(image_like, [])

    def test_check_fails_when_reports_not_yet_produced(self):
        with self.assertRaises(spd.ScanError):
            spd.cmd_check(self._args())


class TestPublishReportsAtomically(_ScanFixtureTestCase):
    def test_publishes_all_files_together(self):
        dest_a = self.repo / "a.json"
        dest_b = self.repo / "b.json"
        spd.publish_reports_atomically({dest_a: b'{"x":1}', dest_b: b'{"y":2}'})
        self.assertTrue(dest_a.exists())
        self.assertTrue(dest_b.exists())

    def test_refuses_to_overwrite_existing(self):
        dest_a = self.repo / "a.json"
        dest_a.write_bytes(b"existing")
        with self.assertRaises(spd.ScanError):
            spd.publish_reports_atomically({dest_a: b'{"x":1}'})
        self.assertEqual(dest_a.read_bytes(), b"existing")

    def test_failure_on_second_file_rolls_back_the_first(self):
        dest_a = self.repo / "sub" / "a.json"
        dest_b = self.repo / "sub" / "b.json"
        real_link = spd.os.link
        call_count = {"n": 0}

        def flaky_link(src, dst):
            call_count["n"] += 1
            if call_count["n"] == 2:
                raise OSError("injected")
            return real_link(src, dst)

        with mock.patch.object(spd.os, "link", side_effect=flaky_link):
            with self.assertRaises(OSError):
                spd.publish_reports_atomically({dest_a: b"1", dest_b: b"2"})
        self.assertFalse(dest_a.exists())
        self.assertFalse(dest_b.exists())
        leftovers = list((self.repo / "sub").glob("*.tmp*"))
        self.assertEqual(leftovers, [])


class _RealScanFixtureTestCase(unittest.TestCase):
    """A tiny but REAL fixture: real decodable synthetic images (never a
    real dataset photograph), real sha256 values matching them, one forced
    guaranteed perceptual duplicate across expansion_train/final_test, and
    a real cmd_scan() run producing all five reports (published atomically
    to disk, then re-loadable exactly like the real (never-run-here)
    pipeline would)."""

    def setUp(self):
        self._tmpdir = tempfile.TemporaryDirectory()
        self.repo = Path(self._tmpdir.name)
        self.fx = build_tiny_review_fixture(self, self.repo, slugs=("fx-species-a",), n_final_test=2,
                                            per_slug=1, per_bucket=2, real_images=True)
        self.verified = mrc.load_and_verify_contract(self.repo)
        self.scan_result = spd.cmd_scan(self._args())

    def tearDown(self):
        self._tmpdir.cleanup()

    def _args(self, **overrides):
        d = dict(repo=self.repo)
        d.update(overrides)
        return argparse.Namespace(**d)

    def _report_paths(self) -> dict[str, Path]:
        return {name: self.repo / mrc.APPROVED_OUTPUT_PATHS[name] for name in mrc.SCAN_REPORT_NAMES}

    def _load_reports(self) -> dict[str, dict]:
        return {name: json.loads(p.read_text(encoding="utf-8")) for name, p in self._report_paths().items()}

    def _rechain_and_write(self, reports: dict) -> None:
        """After mutating perceptual_hashes_report and/or
        metadata_leakage_report and/or candidate_pairs_report content,
        propagate fresh content_sha256 values through every downstream
        cross-report binding and rewrite all five files -- so the schema/
        binding layer (mrc.validate_scan_report_bundle) stays internally
        self-consistent and ONLY validate_reports_against_population's
        re-derivation against the real frozen manifests can catch the
        planted defect."""
        hashes_report = reports["perceptual_hashes_report"]
        hashes_report["content_sha256"] = mrc.compute_content_sha256(hashes_report["content"])

        cp_report = reports["candidate_pairs_report"]
        cp_report["content"]["hashes_report_content_sha256"] = hashes_report["content_sha256"]
        cp_report["content_sha256"] = mrc.compute_content_sha256(cp_report["content"])

        leakage_report = reports["metadata_leakage_report"]
        leakage_report["content_sha256"] = mrc.compute_content_sha256(leakage_report["content"])

        ds_report = reports["domain_summary_report"]
        ds_report["content"]["candidate_pairs_report_content_sha256"] = cp_report["content_sha256"]
        ds_report["content"]["metadata_leakage_report_content_sha256"] = leakage_report["content_sha256"]
        ds_report["content_sha256"] = mrc.compute_content_sha256(ds_report["content"])

        ss_report = reports["stop_status_report"]
        ss_report["content"]["domain_summary_report_content_sha256"] = ds_report["content_sha256"]
        ss_report["content_sha256"] = mrc.compute_content_sha256(ss_report["content"])

        for name, path in self._report_paths().items():
            path.write_text(json.dumps(reports[name], indent=2, sort_keys=True) + "\n", encoding="utf-8")


class _PreScanFixtureTestCase(unittest.TestCase):
    """Same tiny real fixture as _RealScanFixtureTestCase, but cmd_scan()
    is NOT run in setUp -- tests here run it themselves, usually with an
    injected in-memory defect, to prove a pre-publication check catches it
    before any of the five report files are written."""

    def setUp(self):
        self._tmpdir = tempfile.TemporaryDirectory()
        self.repo = Path(self._tmpdir.name)
        self.fx = build_tiny_review_fixture(self, self.repo, slugs=("fx-species-a",), n_final_test=2,
                                            per_slug=1, per_bucket=2, real_images=True)
        self.verified = mrc.load_and_verify_contract(self.repo)

    def tearDown(self):
        self._tmpdir.cleanup()

    def _args(self, **overrides):
        d = dict(repo=self.repo)
        d.update(overrides)
        return argparse.Namespace(**d)

    def _assert_nothing_published(self):
        for name in mrc.SCAN_REPORT_NAMES:
            self.assertFalse((self.repo / mrc.APPROVED_OUTPUT_PATHS[name]).exists(),
                             f"{name} must not exist after a rejected pre-publication scan")
        leftovers = list(self.repo.glob("training/*.tmp*"))
        self.assertEqual(leftovers, [], "no temp files may be left behind")


class TestScanPrePublicationValidation(_PreScanFixtureTestCase):
    """Item 1: cmd_scan must call validate_reports_against_population on
    the in-memory reports, before publish_reports_atomically, so a defect
    that structural validation alone would miss still blocks publication
    entirely (all five files, all-or-nothing) -- and a corrected later
    --scan remains possible (nothing left behind to collide with it)."""

    # Each test below intercepts _report_envelope to corrupt ONLY the
    # in-memory content of one already-assembled report (never the shared
    # `hashes`/`candidate_domains`/`rows_by_part` values pair generation
    # itself depends on, which would crash the pipeline instead of
    # exercising validation) and bypasses the pre-existing structural
    # layer (mrc.validate_scan_report_bundle) so the defect can ONLY be
    # caught by the NEW validate_reports_against_population call -- proving
    # that call is actually wired in and actually blocks publication.

    def _mutate_hashes_report(self, content):
        content = dict(content)
        hashes = dict(content["hashes"])
        del hashes[next(iter(hashes))]  # drop one real identity's hash entry
        content["hashes"] = hashes
        return content

    def _mutate_candidate_pairs_report_drop_pair(self, content):
        content = dict(content)
        domains = dict(content["domains"])
        for name, pairs in domains.items():
            if pairs:
                domains[name] = pairs[1:]  # silently drop one real candidate
                break
        content["domains"] = domains
        return content

    def _mutate_candidate_pairs_report_change_distance(self, content):
        content = dict(content)
        domains = dict(content["domains"])
        for name, pairs in domains.items():
            if pairs:
                new_pairs = list(pairs)
                new_pairs[0] = {**new_pairs[0],
                                "dhash_distance": min(new_pairs[0]["dhash_distance"] + 1, mrc.DHASH_BITS)}
                domains[name] = new_pairs
                break
        content["domains"] = domains
        return content

    def _mutate_domain_summary_report_wrong_count(self, content):
        content = dict(content)
        domains = dict(content["domains"])
        name, entry = next(iter(domains.items()))
        domains[name] = {**entry, "a_count": entry["a_count"] + 1}
        content["domains"] = domains
        return content

    def _run_with_content_mutation(self, detect, mutate):
        real_envelope = spd._report_envelope

        def patched(content):
            if detect(content):
                content = mutate(content)
            return real_envelope(content)

        with mock.patch.object(mrc, "validate_scan_report_bundle", return_value=[]):
            with mock.patch.object(spd, "_report_envelope", side_effect=patched):
                with self.assertRaises(spd.ScanError) as ctx:
                    spd.cmd_scan(self._args())
        self.assertIn("re-derivation", str(ctx.exception))
        self._assert_nothing_published()

    def test_missing_hash_identity_blocks_publication(self):
        self._run_with_content_mutation(lambda c: "hashes" in c, self._mutate_hashes_report)

    def test_omitted_candidate_blocks_publication(self):
        self._run_with_content_mutation(lambda c: "hashes_report_content_sha256" in c,
                                        self._mutate_candidate_pairs_report_drop_pair)

    def test_changed_distance_blocks_publication(self):
        self._run_with_content_mutation(lambda c: "hashes_report_content_sha256" in c,
                                        self._mutate_candidate_pairs_report_change_distance)

    def test_wrong_population_count_blocks_publication(self):
        self._run_with_content_mutation(lambda c: "candidate_pairs_report_content_sha256" in c,
                                        self._mutate_domain_summary_report_wrong_count)

    def test_uncorrupted_scan_still_succeeds(self):
        # Sanity check: the fixture/mocking machinery itself doesn't
        # accidentally break a normal, uncorrupted scan.
        result = spd.cmd_scan(self._args())
        self.assertTrue(result["ok"])
        for name in mrc.SCAN_REPORT_NAMES:
            self.assertTrue((self.repo / mrc.APPROVED_OUTPUT_PATHS[name]).exists())

    def test_corrected_later_scan_succeeds_after_a_rejected_one(self):
        real_envelope = spd._report_envelope

        def patched(content):
            if "hashes" in content:
                content = self._mutate_hashes_report(content)
            return real_envelope(content)

        with mock.patch.object(mrc, "validate_scan_report_bundle", return_value=[]):
            with mock.patch.object(spd, "_report_envelope", side_effect=patched):
                with self.assertRaises(spd.ScanError):
                    spd.cmd_scan(self._args())
        self._assert_nothing_published()

        # Nothing left behind to collide with -- an uncorrupted rerun works.
        result = spd.cmd_scan(self._args())
        self.assertTrue(result["ok"])


class TestRealScanEndToEnd(_RealScanFixtureTestCase):
    def test_scan_reports_ok_and_forced_duplicate_is_a_candidate(self):
        self.assertTrue(self.scan_result["ok"])
        self.assertEqual(set(self.scan_result["reports"]), set(mrc.SCAN_REPORT_NAMES))
        cp_path = Path(self.scan_result["reports"]["candidate_pairs_report"]["path"])
        cp_report = json.loads(cp_path.read_text(encoding="utf-8"))
        pairs = cp_report["content"]["domains"]["benchmark_v1_vs_final_test"]
        self.assertGreaterEqual(len(pairs), 1)
        self.assertTrue(any(p["phash_distance"] == 0 and p["dhash_distance"] == 0 for p in pairs))

    def test_check_accepts_the_freshly_published_bundle(self):
        result = spd.cmd_check(self._args())
        self.assertTrue(result["ok"])
        self.assertEqual(len(result["reports"]), 5)

    def test_check_rejects_mutation_even_after_rehash(self):
        # A mutated-then-rehashed report must still fail: the validators
        # check semantic derivation (cross-report bindings, recomputed
        # pair_ids/counts), not merely self-consistent content_sha256.
        path = self.repo / mrc.APPROVED_OUTPUT_PATHS["candidate_pairs_report"]
        report = json.loads(path.read_text(encoding="utf-8"))
        # Fabricate an extra pair with a bogus (non-recomputable) pair_id.
        report["content"]["domains"]["within_final_test"].append({
            "pair_id": "0" * 64, "identity_a": "x", "identity_b": "y",
            "phash_distance": 1, "dhash_distance": 1,
        })
        report["content_sha256"] = mrc.compute_content_sha256(report["content"])
        path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        with self.assertRaises(spd.ScanError):
            spd.cmd_check(self._args())

    def test_scan_never_calls_bruteforce(self):
        import inspect
        source = inspect.getsource(spd.cmd_scan)
        # Only its own docstring may mention the name; it must never be
        # CALLED (i.e. never appear followed by an opening paren).
        self.assertNotIn("generate_candidate_pairs_bruteforce(", source)

    # ---- item 3: genuinely-derived --check, re-chained after mutation ----
    def test_empty_bundle_mutate_and_rehash_rejected(self):
        # A fully empty (but internally rehashed and cross-bound) bundle
        # must never pass just because every hash is self-consistent.
        reports = self._load_reports()
        reports["perceptual_hashes_report"]["content"]["hashes"] = {}
        reports["metadata_leakage_report"]["content"]["findings"] = []
        for name in mrc.SCAN_REPORT_NAMES[2:]:
            content = reports[name]["content"]
            if "domains" in content:
                for domain_name in list(content["domains"]):
                    entry = content["domains"][domain_name]
                    if isinstance(entry, list):
                        content["domains"][domain_name] = []
                    elif isinstance(entry, dict):
                        if "candidate_count" in entry:
                            entry.update(a_count=0, b_count=0, candidate_count=0, leakage_count=0)
                        elif "stop_before_inference" in entry:
                            entry.update(stop_before_inference=False, reasons=[])
        reports["stop_status_report"]["content"]["overall_stop_before_inference"] = False
        self._rechain_and_write(reports)
        with self.assertRaises(spd.ScanError) as ctx:
            spd.cmd_check(self._args())
        self.assertIn("re-derivation", str(ctx.exception))

    def test_missing_hash_entry_rejected(self):
        reports = self._load_reports()
        hashes = reports["perceptual_hashes_report"]["content"]["hashes"]
        removed_identity = next(iter(hashes))
        del hashes[removed_identity]
        self._rechain_and_write(reports)
        with self.assertRaises(spd.ScanError):
            spd.cmd_check(self._args())

    def test_invented_pair_rejected(self):
        reports = self._load_reports()
        hashes = reports["perceptual_hashes_report"]["content"]["hashes"]
        any_identity = next(iter(hashes))
        domains = reports["candidate_pairs_report"]["content"]["domains"]
        domains["within_final_test"].append({
            "pair_id": mrc.compute_pair_id(any_identity, "not-a-real-identity"),
            "identity_a": any_identity, "identity_b": "not-a-real-identity",
            "phash_distance": 0, "dhash_distance": 0,
        })
        self._rechain_and_write(reports)
        with self.assertRaises(spd.ScanError):
            spd.cmd_check(self._args())

    def test_omitted_real_pair_rejected(self):
        reports = self._load_reports()
        domains = reports["candidate_pairs_report"]["content"]["domains"]
        pairs = domains["benchmark_v1_vs_final_test"]
        self.assertGreaterEqual(len(pairs), 1, "fixture must have the forced duplicate candidate")
        domains["benchmark_v1_vs_final_test"] = pairs[1:]  # drop a real candidate
        self._rechain_and_write(reports)
        with self.assertRaises(spd.ScanError):
            spd.cmd_check(self._args())

    def test_changed_distance_rejected(self):
        reports = self._load_reports()
        pairs = reports["candidate_pairs_report"]["content"]["domains"]["benchmark_v1_vs_final_test"]
        pairs[0]["dhash_distance"] = min(pairs[0]["dhash_distance"] + 1, mrc.DHASH_BITS)
        self._rechain_and_write(reports)
        with self.assertRaises(spd.ScanError):
            spd.cmd_check(self._args())

    def test_duplicate_pair_id_rejected(self):
        reports = self._load_reports()
        domains = reports["candidate_pairs_report"]["content"]["domains"]
        pair = domains["benchmark_v1_vs_final_test"][0]
        domains["within_final_test"].append(dict(pair))  # same pair_id, different domain
        self._rechain_and_write(reports)
        with self.assertRaises(spd.ScanError):
            spd.cmd_check(self._args())

    def test_wrong_domain_membership_rejected(self):
        reports = self._load_reports()
        domains = reports["candidate_pairs_report"]["content"]["domains"]
        # Take the real forced-duplicate pair (benchmark_v1/final_test
        # identities) and relabel it into a domain neither identity
        # actually belongs to.
        source_pairs = domains["benchmark_v1_vs_final_test"]
        self.assertGreaterEqual(len(source_pairs), 1, "fixture must have the forced duplicate candidate")
        stolen = dict(source_pairs[0])
        domains["benchmark_v1_vs_final_test"] = source_pairs[1:]
        domains["calibration_v1_vs_calibration_v2"].append(stolen)
        self._rechain_and_write(reports)
        with self.assertRaises(spd.ScanError):
            spd.cmd_check(self._args())

    def test_wrong_a_count_rejected(self):
        reports = self._load_reports()
        entry = reports["domain_summary_report"]["content"]["domains"]["within_final_test"]
        entry["a_count"] = entry["a_count"] + 1
        entry["b_count"] = entry["a_count"]
        self._rechain_and_write(reports)
        with self.assertRaises(spd.ScanError):
            spd.cmd_check(self._args())

    def test_wrong_b_count_rejected(self):
        reports = self._load_reports()
        entry = reports["domain_summary_report"]["content"]["domains"]["benchmark_v1_vs_final_test"]
        entry["b_count"] = entry["b_count"] + 1
        self._rechain_and_write(reports)
        with self.assertRaises(spd.ScanError):
            spd.cmd_check(self._args())


class TestAdjudicationHashBinding(_RealScanFixtureTestCase):
    def setUp(self):
        super().setUp()
        cp_path = self.repo / mrc.APPROVED_OUTPUT_PATHS["candidate_pairs_report"]
        self.data = cp_path.read_bytes()
        cp_report = json.loads(self.data.decode("utf-8"))
        self.scan_content_sha256 = cp_report["content_sha256"]
        self.report_sha256 = mrc.sha256_bytes(self.data)
        pairs = cp_report["content"]["domains"]["benchmark_v1_vs_final_test"]
        self.candidate_row = pairs[0]
        self.pair_id = self.candidate_row["pair_id"]

    def _valid_fields(self, **overrides):
        fields = adj.build_adjudication_fields(
            {**self.candidate_row, "domain": "benchmark_v1_vs_final_test"},
            self.report_sha256, self.scan_content_sha256,
            label="different_photo_same_observation", reviewer_id="r1", session_id="s1",
            reviewed_at_utc="2026-01-01T00:00:00Z")
        fields.update(overrides)
        return fields

    def test_valid_adjudication_recorded(self):
        record = adj.record_adjudication(self.repo, self._valid_fields())
        self.assertEqual(record["pair_id"], self.pair_id)

    def test_mismatched_identity_a_rejected(self):
        fields = self._valid_fields(identity_a="something-else")
        with self.assertRaises(adj.AdjudicationError):
            adj.record_adjudication(self.repo, fields)

    def test_mismatched_domain_rejected(self):
        fields = self._valid_fields(domain="within_benchmark_v1")
        with self.assertRaises(adj.AdjudicationError):
            adj.record_adjudication(self.repo, fields)

    def test_mismatched_phash_distance_rejected(self):
        fields = self._valid_fields(phash_distance=999)
        with self.assertRaises(adj.AdjudicationError):
            adj.record_adjudication(self.repo, fields)

    def test_stale_report_hash_rejected_after_report_changes(self):
        # Adjudicate successfully once, then the candidate-pairs report
        # file is rewritten (e.g. republished with different formatting --
        # its PARSED content, and therefore content_sha256 and population
        # re-derivation, are unchanged) -- a NEW adjudication bound to the
        # OLD raw-byte hash must be rejected even for the SAME pair_id
        # shape and unchanged content.
        stale_fields = self._valid_fields()
        path = self.repo / mrc.APPROVED_OUTPUT_PATHS["candidate_pairs_report"]
        report = json.loads(path.read_text(encoding="utf-8"))
        path.write_text(json.dumps(report, indent=4, sort_keys=True) + "\n", encoding="utf-8")
        with self.assertRaises(adj.AdjudicationError) as ctx:
            adj.record_adjudication(self.repo, stale_fields)
        self.assertIn("candidate_pairs_report_sha256", str(ctx.exception))

    def test_free_form_label_rejected(self):
        fields = self._valid_fields(label="looks_similar")
        with self.assertRaises(adj.AdjudicationError):
            adj.record_adjudication(self.repo, fields)

    def test_duplicate_pair_adjudication_rejected(self):
        adj.record_adjudication(self.repo, self._valid_fields())
        with self.assertRaises(adj.AdjudicationError):
            adj.record_adjudication(self.repo, self._valid_fields())

    def test_unknown_pair_id_rejected(self):
        fields = self._valid_fields(pair_id="0" * 64)
        with self.assertRaises(adj.AdjudicationError):
            adj.record_adjudication(self.repo, fields)

    def test_confirmed_same_source_pairs_reads_back_correctly(self):
        adj.record_adjudication(self.repo, self._valid_fields(label="same_source_image"))
        confirmed = adj.confirmed_same_source_pairs(self.repo)
        self.assertEqual(len(confirmed), 1)

    def test_cmd_next_and_cmd_record_cli(self):
        result = adj.cmd_next(self._args())
        self.assertFalse(result["done"])
        self.assertEqual(result["pair_id"], self.pair_id)

        args = self._args(pair_id=self.pair_id, label="different_image", reviewer_id="r1",
                          session_id="s1", reviewed_at_utc="2026-01-01T00:00:00Z", notes="")
        result = adj.cmd_record(args)
        self.assertTrue(result["recorded"])

        result = adj.cmd_next(self._args())
        self.assertTrue(result["done"])

    def test_cmd_preflight_reports_progress(self):
        result = adj.cmd_preflight(self._args())
        self.assertEqual(result["total_candidates"], 1)
        self.assertEqual(result["remaining_count"], 1)

    # ---- item 2: every adjudicate_pairs.py mode uses the SHARED loader --
    def test_all_modes_reject_a_mutate_and_rehash_candidate_report_before_writing_the_ledger(self):
        # A candidate-pairs report that passes its own local envelope
        # checks (mrc.validate_candidate_pairs_report: recomputable
        # pair_id, in-range distances, satisfies the candidate rule) but
        # disagrees with the deterministic recomputation from the real
        # reported hashes -- only population re-derivation catches this.
        # Every adjudicate_pairs.py mode must reject it BEFORE writing
        # anything to the ledger, never fall back to the weaker
        # candidate-report-only check.
        reports = self._load_reports()
        pairs = reports["candidate_pairs_report"]["content"]["domains"]["benchmark_v1_vs_final_test"]
        for pair in pairs:
            if pair["pair_id"] == self.pair_id:
                pair["dhash_distance"] = 1  # still in-range, still satisfies the candidate rule
        self._rechain_and_write(reports)

        # Sanity: the mutated report alone still passes its own local
        # envelope check (proving the OLD weaker path would have accepted
        # it) -- only the full population re-derivation may catch this.
        mutated_cp_report = json.loads(
            (self.repo / mrc.APPROVED_OUTPUT_PATHS["candidate_pairs_report"]).read_text(encoding="utf-8"))
        mutated_hashes_report = json.loads(
            (self.repo / mrc.APPROVED_OUTPUT_PATHS["perceptual_hashes_report"]).read_text(encoding="utf-8"))
        local_problems = mrc.validate_candidate_pairs_report(
            mutated_cp_report, self.verified["contract"], mutated_hashes_report["content_sha256"])
        self.assertEqual(local_problems, [], "test setup invalid: mutation must pass the local envelope check")

        ledger_path = adj.ledger_path_for(self.repo)
        self.assertFalse(ledger_path.exists())

        with self.assertRaises(spd.ScanError):
            adj.cmd_preflight(self._args())
        with self.assertRaises(spd.ScanError):
            adj.cmd_next(self._args())
        record_args = self._args(pair_id=self.pair_id, label="different_image", reviewer_id="r1",
                                 session_id="s1", reviewed_at_utc="2026-01-01T00:00:00Z", notes="")
        with self.assertRaises(spd.ScanError):
            adj.cmd_record(record_args)

        self.assertFalse(ledger_path.exists(), "no mode may write to the ledger against unverified state")


class TestAdjudicationLedgerSemanticVerification(_RealScanFixtureTestCase):
    """Item 3/6: every adjudicate_pairs.py working mode must semantically
    re-verify EXISTING ledger records against the fully verified candidate
    row -- not merely trust generic hash-chain verification."""

    def setUp(self):
        super().setUp()
        cp_path = self.repo / mrc.APPROVED_OUTPUT_PATHS["candidate_pairs_report"]
        self.cp_bytes = cp_path.read_bytes()
        cp_report = json.loads(self.cp_bytes.decode("utf-8"))
        self.report_sha256 = mrc.sha256_bytes(self.cp_bytes)
        self.scan_content_sha256 = cp_report["content_sha256"]
        pairs = cp_report["content"]["domains"]["benchmark_v1_vs_final_test"]
        self.candidate_row = pairs[0]
        self.pair_id = self.candidate_row["pair_id"]

    def _record_one_valid_adjudication(self) -> None:
        fields = adj.build_adjudication_fields(
            {**self.candidate_row, "domain": "benchmark_v1_vs_final_test"},
            self.report_sha256, self.scan_content_sha256,
            label="different_image", reviewer_id="r1", session_id="s1",
            reviewed_at_utc="2026-01-01T00:00:00Z")
        adj.record_adjudication(self.repo, fields)

    def _tamper_and_rehash_single_record(self, **field_overrides) -> bytes:
        """Records one valid adjudication, then rewrites the ledger with
        an identity/binding field altered (pair_id unchanged) and the
        record_hash recomputed so generic verify_chain still passes --
        simulates a record edited outside this tool. Returns the ledger's
        raw bytes AFTER tampering, for later byte-identity comparison."""
        self._record_one_valid_adjudication()
        ledger_path = adj.ledger_path_for(self.repo)
        record = json.loads(ledger_path.read_text(encoding="utf-8").strip())
        record.update(field_overrides)
        payload = {k: v for k, v in record.items() if k != "record_hash"}
        record["record_hash"] = mrc.sha256_bytes(mrc.canonical_json_bytes(payload))
        ledger_path.write_text(json.dumps(record, sort_keys=True, separators=(",", ":")) + "\n",
                               encoding="utf-8")
        return ledger_path.read_bytes()

    def test_mutate_and_rehash_identity_rejected_by_every_mode_and_ledger_unchanged(self):
        tampered_bytes = self._tamper_and_rehash_single_record(identity_a="not-the-real-identity")

        with self.assertRaises(adj.AdjudicationError):
            adj.cmd_preflight(self._args())
        with self.assertRaises(adj.AdjudicationError):
            adj.cmd_next(self._args())
        with self.assertRaises(adj.AdjudicationError):
            adj.cmd_status(self._args())

        record_args = self._args(pair_id=self.pair_id, label="different_image", reviewer_id="r1",
                                 session_id="s1", reviewed_at_utc="2026-01-01T00:00:00Z", notes="")
        with self.assertRaises(adj.AdjudicationError):
            adj.cmd_record(record_args)

        self.assertEqual(adj.ledger_path_for(self.repo).read_bytes(), tampered_bytes)

    def test_mutate_and_rehash_domain_rejected(self):
        self._tamper_and_rehash_single_record(domain="within_calibration_v1")
        with self.assertRaises(adj.AdjudicationError):
            adj.cmd_preflight(self._args())

    def test_mutate_and_rehash_distance_rejected(self):
        self._tamper_and_rehash_single_record(
            dhash_distance=min(self.candidate_row["dhash_distance"] + 1, mrc.DHASH_BITS))
        with self.assertRaises(adj.AdjudicationError):
            adj.cmd_preflight(self._args())

    def test_mutate_and_rehash_report_binding_rejected(self):
        self._tamper_and_rehash_single_record(candidate_pairs_report_sha256="0" * 64)
        with self.assertRaises(adj.AdjudicationError):
            adj.cmd_preflight(self._args())

    def test_confirmed_same_source_pairs_rejects_a_tainted_ledger(self):
        # Confirmed same-source findings must never be derived from raw,
        # unverified ledger state.
        self._tamper_and_rehash_single_record(identity_b="not-the-real-identity")
        with self.assertRaises(adj.AdjudicationError):
            adj.confirmed_same_source_pairs(self.repo)

    def test_cmd_preflight_never_returns_ok_true_with_a_tainted_ledger(self):
        self._tamper_and_rehash_single_record(identity_a="not-the-real-identity")
        try:
            result = adj.cmd_preflight(self._args())
        except adj.AdjudicationError:
            return
        self.fail(f"cmd_preflight must raise or never report ok=True on a tainted ledger, got {result!r}")

    def test_interrupted_tail_still_recoverable_by_next_authorized_record(self):
        # Item 5: a genuinely interrupted (non-newline-terminated) final
        # line remains recoverable by the next authorized --record, and
        # read-only modes must not mutate the ledger while tolerating it.
        self._record_one_valid_adjudication()
        ledger_path = adj.ledger_path_for(self.repo)
        with ledger_path.open("a", encoding="utf-8") as fh:
            fh.write('{"pair_id": "trunc')  # interrupted mid-write, no newline

        before = ledger_path.read_bytes()
        result = adj.cmd_preflight(self._args())
        self.assertTrue(result["ok"])
        self.assertEqual(result["adjudicated_count"], 1)
        self.assertEqual(ledger_path.read_bytes(), before, "a read-only mode must never mutate the ledger")

        # cmd_next reports done (the fixture's one real candidate is
        # already adjudicated); nothing further to recover here, but the
        # ledger remains fully usable.
        next_result = adj.cmd_next(self._args())
        self.assertTrue(next_result["done"])


if __name__ == "__main__":
    unittest.main(verbosity=2)
